import { withBasePath } from "@/lib/base-path"
import type { Metadata } from "next"
import { RiCommandLine, RiFolderTransferLine, RiShieldKeyholeLine } from "@remixicon/react"
import { Card, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { ProductHero } from "@/components/startup/hero"
import { SiteFooter } from "@/components/startup/footer"
import { SiteHeader } from "@/components/startup/header"
export const metadata:Metadata={title:"Gate",description:"Bring local MCPs and Skills to ChatGPT."}
const tools=[{icon:RiCommandLine,title:"Streaming commands",copy:"Run local shell commands, inspect output as it arrives and keep work on your own machine."},{icon:RiShieldKeyholeLine,title:"OAuth protected",copy:"Expose one stable MCP endpoint with locally signed tokens and built-in destructive-command safeguards."},{icon:RiFolderTransferLine,title:"Files and Skills",copy:"Share revocable files and discover trusted Agent Skills only when a conversation needs them."}]
export default function Gate(){return <div className="min-h-svh bg-background text-foreground"><SiteHeader/><main className="divide-y divide-border/50"><ProductHero logo={withBasePath("/branding/spel-logo.svg")} badge="Local MCP reverse proxy" title="Your machine, inside ChatGPT." copy="Gate exposes local commands, files, MCP servers and trusted Agent Skills through one OAuth-protected endpoint. Your services stay local. ChatGPT gets a door, not the building." primaryHref="#install" primaryLabel="Install Gate" githubHref="https://github.com/spelcc/gate"><div className="mt-12 w-full max-w-2xl border bg-card p-5 text-left font-mono text-sm shadow-xl"><p className="text-muted-foreground">You</p><p className="mt-1">Restart OpenClaw and show me the last 50 error lines.</p><p className="mt-5 text-primary">Gate</p><p>✓ Connected to your machine<br/>✓ OpenClaw restarted<br/>✓ Logs retrieved</p></div></ProductHero><section id="install" className="px-6 py-20"><div className="mx-auto grid max-w-5xl gap-8 md:grid-cols-2 md:items-center"><div><span className="text-sm uppercase tracking-widest text-muted-foreground">Install</span><h2 className="mt-3 text-3xl font-bold sm:text-4xl">One command. Then talk.</h2><p className="mt-4 text-muted-foreground">macOS, Linux and WSL. A rare case where the one-line installer is not a metaphor.</p></div><pre className="overflow-x-auto border bg-card p-5 text-sm"><code>curl -fsSL https://spel.cc/gate.sh | bash</code></pre></div></section><section className="px-6 py-20 sm:py-28"><div className="mx-auto max-w-5xl"><div className="grid gap-6 md:grid-cols-3">{tools.map(({icon:Icon,title,copy})=><Card key={title} className="p-6"><CardHeader className="p-0"><span className="flex size-11 items-center justify-center border bg-muted"><Icon className="size-5"/></span><CardTitle className="mt-5">{title}</CardTitle><CardDescription className="mt-2 leading-6">{copy}</CardDescription></CardHeader></Card>)}</div></div></section></main><SiteFooter/></div>}
