import { withBasePath } from "@/lib/base-path"
import type { Metadata } from "next"
import { RiDragDropLine, RiMacLine, RiTerminalBoxLine } from "@remixicon/react"
import { Card, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { ProductHero } from "@/components/startup/hero"
import { SiteFooter } from "@/components/startup/footer"
import { SiteHeader } from "@/components/startup/header"
export const metadata:Metadata={title:"Winegold",description:"Drop a file on the screen edge. Pick an action. Done."}
const features=[{icon:RiDragDropLine,title:"Edge drop zone",copy:"Drag files to the right screen edge and open a focused action panel without hunting through menus."},{icon:RiTerminalBoxLine,title:"Local recipes",copy:"Create or import readable .wg.yml actions that run commands with file and folder placeholders."},{icon:RiMacLine,title:"Native macOS app",copy:"Runs from the menu bar, stays local and updates from signed release artifacts with checksum verification."}]
export default function Winegold(){return <div className="min-h-svh bg-background text-foreground"><SiteHeader/><main className="divide-y divide-border/50"><ProductHero logo={withBasePath("/branding/winegold-logo.png")} badge="Native macOS automation" title="Drop a file. Pick an action. Done." copy="Winegold turns the edge of your screen into a local command launcher. Drag files, select a recipe and let the machine do the repetitive part for once." primaryHref="#install" primaryLabel="Install Winegold" githubHref="https://github.com/spelcc/winegold"/><section id="install" className="px-6 py-20"><div className="mx-auto grid max-w-5xl gap-8 md:grid-cols-2 md:items-center"><div><span className="text-sm uppercase tracking-widest text-muted-foreground">Install</span><h2 className="mt-3 text-3xl font-bold sm:text-4xl">One command on macOS.</h2><p className="mt-4 text-muted-foreground">Community builds are local, open source and may require approval in Privacy & Security because Apple enjoys paperwork.</p></div><pre className="overflow-x-auto border bg-card p-5 text-sm"><code>curl -fsSL https://spel.cc/winegold.sh | bash</code></pre></div></section><section className="px-6 py-20 sm:py-28"><div className="mx-auto max-w-5xl"><div className="grid gap-6 md:grid-cols-3">{features.map(({icon:Icon,title,copy})=><Card key={title} className="p-6"><CardHeader className="p-0"><span className="flex size-11 items-center justify-center border bg-muted"><Icon className="size-5"/></span><CardTitle className="mt-5">{title}</CardTitle><CardDescription className="mt-2 leading-6">{copy}</CardDescription></CardHeader></Card>)}</div><div className="mt-12 border bg-card p-6"><p className="text-sm font-medium">Example recipe</p><pre className="mt-4 overflow-x-auto text-sm text-muted-foreground"><code>{`name: Copy file path
trigger:
cmd:
  exec: 'echo "{input}" | pbcopy'`}</code></pre></div></div></section></main><SiteFooter/></div>}
